Version 1.2.3: Added automatic detection of zram devices available

diff --git a/stormbyte-stagemanager b/stormbyte-stagemanager
--- a/stormbyte-stagemanager
+++ b/stormbyte-stagemanager
@@ -13,7 +13,7 @@ fi
 
 loadConfig
 
-version="1.2.2"
+version="1.2.3"
 current_folder=`pwd`
 file_list=(`find "${TARBALL_FOLDER}" -type f \( -iname "*.tar.gz" -o -iname "*.tgz" -o -iname "*.tar.bz2" -o -iname "*.tbz2" -o -iname "*.tar.xz" -o -iname "*.txz" -o -iname "*.tar.zstd" -o -iname "*.tzd" \)`)
 tarball_filename_fullpath=""
@@ -34,6 +34,7 @@ output_folder=""
 available_commands=(list use rebase convert export delete rename download copy help notes)
 available_compression_formats=( gzip bzip2 xz zstd )
 available_compression_extensions=( tar.gz tgz tar.bz2 tbz2 tar.xz txz tar.zstd tzd )
+zram_device=""
 
 function header() {
 	echo "StormByte Gentoo Stage Manager Version ${version}"
@@ -345,10 +346,16 @@ function mountFOLDER() {
 
 function mountZRAM() {
 	mkdir -p "${tmp_folder}"
-	handleCommand "echo 1 > /sys/block/zram0/reset" "Resetting ZRAM..."
-	handleCommand "echo '${STORAGE_SIZE}' > /sys/block/zram0/disksize" "Setting ZRAM size to ${STORAGE_SIZE}..."
-	handleCommand "mkfs.btrfs /dev/zram0" "Initializing ZRAM with btrfs..."
-	handleCommand "mount /dev/zram0 '${tmp_folder}' -o noatime,compress=zstd" "Mounting ZRAM storage"
+	zram_device_full=`zramctl -f`
+	zram_device=`basename "${zram_device_full}"`
+	if [ -z "${zram_device}" ]; then
+		echo "ERROR: There are no ZRAM devices available";
+		exit 1;
+	fi
+	handleCommand "echo 1 > /sys/block/${zram_device}/reset" "Resetting ZRAM..."
+	handleCommand "echo '${STORAGE_SIZE}' > /sys/block/${zram_device}/disksize" "Setting ZRAM size to ${STORAGE_SIZE}..."
+	handleCommand "mkfs.btrfs ${zram_device_full}" "Initializing ${zram_device} with btrfs..."
+	handleCommand "mount ${zram_device_full} '${tmp_folder}' -o noatime,compress=zstd" "Mounting ${zram_device} storage"
 }
 
 function mountTMPFS() {
@@ -363,8 +370,8 @@ function unmountFOLDER() {
 
 function unmountZRAM() {
 	cd "${current_folder}"
-	handleCommand "umount -R ${tmp_folder}" "Unmounting ZRAM storage"
-	handleCommand "echo 1 > /sys/block/zram0/reset" "Deactivating ZRAM..."
+	handleCommand "umount -R ${tmp_folder}" "Unmounting ${zram_device} storage"
+	handleCommand "echo 1 > /sys/block/${zram_device}/reset" "Deactivating ${zram_device}..."
 }
 
 function unmountTMPFS() {
