Use ext2+zram compression instead of btrfs to reduce overhead

diff --git a/StormByte-StageManager b/StormByte-StageManager
--- a/StormByte-StageManager
+++ b/StormByte-StageManager
@@ -349,11 +349,17 @@ function checkVars() {
 		fi
 	fi
 	if [ "${STORAGE_SYSTEM}" = "zram" ]; then
-		if ! [ -z "${STORAGE_SYSTEM_ZRAM_COMPRESSION_LEVEL}" ]; then
-			if [ "${STORAGE_SYSTEM_ZRAM_COMPRESSION_LEVEL}" -lt 0 ] || [ "${STORAGE_SYSTEM_ZRAM_COMPRESSION_LEVEL}" -gt 15 ]; then
-				echo "${_CLR_RED}  ✗${_CLR_RESET} STORAGE_SYSTEM_ZRAM_COMPRESSION_LEVEL has a value which is less than 0 or greater than 15"
-				errors=1
-			fi
+		if ! [ -z "${STORAGE_SYSTEM_ZRAM_COMPRESSION_ALGO}" ]; then
+			case "${STORAGE_SYSTEM_ZRAM_COMPRESSION_ALGO}" in
+				zstd|lz4|lz4hc)
+					# Valid algorithm → do nothing
+					;;
+				*)
+					echo "${_CLR_RED}  ✗${_CLR_RESET} STORAGE_SYSTEM_ZRAM_COMPRESSION_ALGO='${STORAGE_SYSTEM_ZRAM_COMPRESSION_ALGO}' is invalid." >&2
+					echo "   Available values are: zstd, lz4, lz4hc" >&2
+					errors=1
+					;;
+			esac
 		fi
 	fi
 
@@ -788,23 +794,26 @@ function mountFOLDER() {
 ##
 # @brief Mounts a ZRAM-based temporary storage.
 ##
-function mountZRAM() {
-	mkdir -p "${tmp_folder}"
-	zram_device_full=`zramctl -f`
-	zram_device=`basename "${zram_device_full}"`
-	zram_zstd_compression=""
-	if [ -z "${zram_device}" ]; then
-		displayError "There are no ZRAM devices available"
-	fi
-	if [ -z "${STORAGE_SYSTEM_ZRAM_COMPRESSION_LEVEL}" ]; then
-		zram_zstd_compression="zstd"
-	else
-		zram_zstd_compression="zstd:${STORAGE_SYSTEM_ZRAM_COMPRESSION_LEVEL}"
-	fi
-	handleCommand "echo 1 > /sys/block/${zram_device}/reset" "Resetting ZRAM"
-	handleCommand "echo '${STORAGE_SIZE}' > /sys/block/${zram_device}/disksize" "Setting ZRAM size to ${STORAGE_SIZE}"
-	handleCommand "mkfs.btrfs --checksum ${BTRFS_CHECKSUM} ${zram_device_full}" "Initializing ${zram_device} with btrfs"
-	handleCommand "mount ${zram_device_full} '${tmp_folder}' -o noatime,nodiratime,nodatacow,commit=300,autodefrag,compress=${zram_zstd_compression}" "Mounting ${zram_device} storage with compression ${zram_zstd_compression}"
+mountZRAM() {
+    mkdir -p "${tmp_folder}"
+    zram_device_full=$(zramctl -f)
+    zram_device=$(basename "${zram_device_full}")
+
+    if [ -z "${zram_device}" ]; then
+        displayError "There are no ZRAM devices available"
+        return 1
+    fi
+
+    handleCommand "echo 1 > /sys/block/${zram_device}/reset" "Resetting ZRAM"
+    handleCommand "echo '${STORAGE_SIZE}' > /sys/block/${zram_device}/disksize" "Setting ZRAM size"
+
+    # Only apply compression if the variable has a value
+    if [ -n "${STORAGE_SYSTEM_ZRAM_COMPRESSION_ALGO}" ]; then
+        handleCommand "echo '${STORAGE_SYSTEM_ZRAM_COMPRESSION_ALGO}' > /sys/block/${zram_device}/comp_algorithm" "Setting compression to ${STORAGE_SYSTEM_ZRAM_COMPRESSION_ALGO}"
+    fi
+
+    handleCommand "mkfs.ext2 -F -q ${zram_device_full}" "Creating ext2 on ZRAM"
+    handleCommand "mount -t ext2 -o noatime,nodiratime,discard ${zram_device_full} '${tmp_folder}'" "Mounting ext2 on ZRAM"
 }
 
 ##
